### ISSUE TITLE
forking leveldown into leveldown-hyper

### ISSUE THREAD

**Issue by ralphtheninja** [Level/leveldown-hyper#1]
I'd like to get hyperdex up and running on latest master so I think I'll start from current tip of master and pull in changes piece by piece.

I think we  should:

- [x] remove `.gitmodules`, the hyperdex code should be at the fingertips
- [x] make it work https://github.com/Level/leveldown-hyper/pull/2
- [x] update docs on `liveBackup()`
- [x] replace `LevelDOWN` with `LevelDOWNHyper` in docs
- [x] make sure `liveBackup()` is tested properly
- [x] update information in `level-hyper` repository (links in README etc) https://github.com/Level/level-hyper/pull/8
- [x] update `README` with more information on `HyperDex`

Also, since `leveldown-hyper` is just a fork of `leveldown` you can administer them both by using two different remotes instead of two different local clones. This will make it trivial to merge in changes from upstream.

**Comment by ralphtheninja** [comment]
I'll be working on `https://github.com/Level/leveldown-hyper/tree/hyperdex-rewrite` branch. If you want to jump in you can make PRs to that branch.

**Comment by juliangruber** [comment]
+1 +1 +1

**Comment by ralphtheninja** [comment]
It seems the latest version we can use is `1.2.1` which was released nine months ago.

**Comment by ralphtheninja** [comment]
I read that `1.6.0` was api compatible with MongoDB. Would be cool if we could get that updated as well. Read more about it [here](http://hackingdistributed.com/2015/01/12/hyperdex-1.6.0/)

**Comment by jcrugzz** [comment]
@ralphtheninja is the idea to make this backed by `hyperdex` or just the fork of `leveldb` that they use? Curious if we are changing semantics since `hyperdex` itself is a distributed database. I currently use the current `leveldown-hyper` which is why I'm curious. I'm definitely +1 to updating the leveldb version but if you wanted this backed by `hyperdex` I'd like to see that done as a different `leveldown` backend.

**Comment by ralphtheninja** [comment]
@jcrugzz The idea is that `leveldown-hyper` as we know it today (a branch in `leveldown`) would be refactored into its own repository. Think of it as moving out that branch into a separate repository. But it will be based on latest master branch in `leveldown`.

**Comment by ralphtheninja** [comment]
@jcrugzz This will be a different `leveldown` backend, see preview here:

https://github.com/Level/leveldown-hyper/blob/hyperdex-rewrite/leveldown-hyper.js#L10-L16

**Comment by ralphtheninja** [comment]
@jcrugzz To answer your first question (I had to think first). It would be backed by their fork of leveldb, just like it works now :)

**Comment by jcrugzz** [comment]
@ralphtheninja ok cool thanks for the clarification, this sounds awesome. Makes it easier to see the code etc :).

**Comment by ralphtheninja** [comment]
@jcrugzz Aye, that's the plan :)
