### ISSUE TITLE
versioning for leveldown-hyper

### ISSUE THREAD

**Issue by ralphtheninja** [Level/leveldown-hyper#10]
I'm not exactly sure on versioning for leveldown-hyper. Simply start with `1.0.0` once everything is fixed?

**Comment by mcollina** [comment]
+1
Il giorno gio 14 mag 2015 alle 16:03 Lars-Magnus Skog <
notifications@github.com> ha scritto:

**Comment by ralphtheninja** [comment]
So be it :)
