### ISSUE TITLE
fails to build on windows

### ISSUE THREAD

**Issue by jcrugzz** [Level/leveldown-hyper#15]
See the following.. https://gist.github.com/jcrugzz/e37c619d504961c85b2b

This seems to be caused by a lack of an `os_include` [here](https://github.com/Level/leveldown-hyper/blob/master/deps/leveldb/leveldb.gyp#L7-L8) because there is no windows conf.

Any idea @ralphtheninja? was using `level-hyper` in a project and found out that windows users cannot use it so i may need to switch to `level` assuming that will build.

**Comment by ralphtheninja** [comment]
I might have missed something while forking leveldown into leveldown-hyper. Let me try to backtrack and see if I can find something. Unfortunately I don't have access to any windows environment so it's hard for me to reproduce atm.

**Comment by rvagg** [comment]
I'm not sure this ever supported windows, the hyperdex guys never had that as a priority or even on their radar when I first pulled it in

**Comment by ralphtheninja** [comment]
I think the best way to go from here is to make sure we have prebuilt binaries for all "official" platforms, at least the basic ones. This is ongoing work for `leveldown` and as soon as I'm done with that, I'll move on to `leveldown-hyper`.

**Comment by jcrugzz** [comment]
thats fair. Didn't know if it could easily support windows as it seems like most of the pieces are there but there could be some gotchas that aren't too apparent. I'll switch over to `level` so my `windows` co-workers will be able to run it and hope it doesn't decrease write perf too much. Thanks to you both!

**Comment by No9** [comment]
So @ralphtheninja as part of the prebuild work we came across this again.
Had a quick glance at the notes from @jcrugzz and tried to create a win conf folder to support the build
This gets past the configuration issue but the build still fails.
We won't have prebuilds for this on windows soon.

**Comment by ralphtheninja** [comment]
I don't think windows will ever happen. There's too little usage of this module for us to go down that road. That said, contributions to make this work is warmly welcome!
