### ISSUE TITLE
Add fixes from leveldown regarding iterator and closing db

### ISSUE THREAD

**Issue by ralphtheninja** [Level/leveldown-hyper#56]
![screenshot from 2018-06-14 22-59-35](https://user-images.githubusercontent.com/308049/41438180-c17e4e96-7026-11e8-8644-9f9b2dbc94ef.png)

**Comment by ralphtheninja** [comment]
Just realized https://github.com/Level/leveldown/pull/323 should be implemented first

**Comment by ralphtheninja** [comment]
Actually, I'd prefer if we moved them afterwards, as a refactoring step.

**Comment by vweevers** [comment]
Is that a matter of priority (do you first want to get leveldown-hyper up to par)? Because I was thinking if we move them into `abstract-leveldown` we could work on seek implementations in parallel. I'm already getting excited about doing that in `memdown` and `level-js` ;)

**Comment by ralphtheninja** [comment]
It's more a matter of juggling two balls than three to me and not about priority. Also, we can do all these things in parallel, i.e. me getting `leveldown-hyper` up to par or moving tests to` abstract-leveldown` shouldn't block you on doing stuff in `memdown` or `level-js`.

**Comment by vweevers** [comment]
> shouldn't block you on doing stuff in memdown or level-js.

If the tests are not in abstract, we'll have duplicates everywhere. Sounds like more balls to me?

**Comment by ralphtheninja** [comment]
I'm not against moving the tests to abstract-leveldown, I'm against me doing it before fixing leveldown-hyper :wink:

**Comment by ralphtheninja** [comment]
My problem right now is getting `leveldown-hyper` up to par with `leveldown`, before even considering updating to latest `abstract-leveldown`. It makes it harder for me to consider both at the same time, that's what I meant by juggling many balls. Moving iterator tests to `abstract-leveldown` can be done in parallel, if that makes more sense.

**Comment by vweevers** [comment]
> getting leveldown-hyper up to par with leveldown, before even considering updating to latest abstract-leveldown

Ahh, I see what you mean now. I'm with you
