### ISSUE TITLE
Update to HyperLevelDB 1.2.2

### ISSUE THREAD

**Issue by ralphtheninja** [Level/leveldown-hyper#9]
Moved out from https://github.com/Level/leveldown-hyper/issues/1

**Comment by ralphtheninja** [comment]
@rvagg Did you generate `leveldb-hyper-conf/$OS/config.h` by running `autoreconf -i` and `./configure` on respective os?

**Comment by rvagg** [comment]
@ralphtheninja no idea! `autoreconf -i` doesn't ring a bell, unless that's what the documentation says to do.
